version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: airflow_postgres
    restart: always
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    ports:
      - "6543:5432"
    volumes:
      - postgres_db_volume:/var/lib/postgresql/data


  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    restart: always

  airflow-webserver:
    image: airflow:dbt  #apache/airflow:2.7.0
    container_name: airflow_webserver
    restart: always
    depends_on:
      - postgres
    environment:
      - AIRFLOW_HOME=/opt/airflow
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
    volumes:
      -  /mnt/c/PythonProject/RealEstate/dags:/opt/airflow/dags:cached
      -  /mnt/c/Users/sawyn/.dbt:/home/airflow/.dbt:cached
      -  /mnt/c/PythonProject/RealEstate/dbt/real_estate_dbt:/opt/airflow/projects/real_estate_dbt:cached
      -  /mnt/c/PythonProject/RealEstate/sql_project:/opt/airflow/projects/sql_project:cached
      -  /mnt/c/PythonProject/RealEstate/logs:/opt/airflow/logs:cached
      -  /mnt/c/PythonProject/RealEstate/plugins:/opt/airflow/plugins:cached
      -  /mnt/c/PythonProject/RealEstate/config.yml:/opt/airflow/config.yml:cached
    ports:
      - "8081:8080"
    command: webserver

  airflow-scheduler:
    image: airflow:dbt #apache/airflow:2.7.0
    container_name: airflow_scheduler
    restart: always
    depends_on:
      - postgres
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
    volumes:
      - /mnt/c/PythonProject/RealEstate/dags:/opt/airflow/dags:cached
      - /mnt/c/Users/sawyn/.dbt:/home/airflow/.dbt:cached
      - /mnt/c/PythonProject/RealEstate/dbt/real_estate_dbt:/opt/airflow/projects/real_estate_dbt:cached
      - /mnt/c/PythonProject/RealEstate/sql_project:/opt/airflow/projects/sql_project:cached
      - /mnt/c/PythonProject/RealEstate/logs:/opt/airflow/logs:cached
      - /mnt/c/PythonProject/RealEstate/plugins:/opt/airflow/plugins:cached
      - /mnt/c/PythonProject/RealEstate/config.yml:/opt/airflow/config.yml:cached

    command: scheduler

  airflow-init:
    image: apache/airflow:2.7.0
    depends_on:
      - postgres
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
    entrypoint: ["/bin/bash", "-c"]
    command:
      - |
        airflow db init

volumes:
  postgres_db_volume:
