version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: airflow_postgres
    restart: always
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    ports:
      - "6543:5432"
    volumes:
      - postgres_db_volume:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_new
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    restart: always

  airflow-webserver:
    image: airflow:dbt
    container_name: airflow_webserver
    env_file:
      - ./.env
    user: "${AIRFLOW_UID}:0"
    restart: always
    depends_on:
      - postgres
    environment:
      AIRFLOW_HOME: /opt/airflow
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
    volumes:
      - airflow_logs:/opt/airflow/logs
      - ./dags:/opt/airflow/dags:cached
      - ./plugins:/opt/airflow/plugins:cached
      - ./config.yml:/opt/airflow/config.yml:cached
      - ./dbt/real_estate_dbt:/opt/airflow/projects/real_estate_dbt:cached
      - ./sql_project:/opt/airflow/projects/sql_project:cached
    ports:
      - "8081:8080"
    command: webserver

  airflow-scheduler:
    image: airflow:dbt
    container_name: airflow_scheduler
    env_file:
      - ./.env
    user: "${AIRFLOW_UID}:0"
    restart: always
    depends_on:
      - postgres
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
    volumes:
      - airflow_logs:/opt/airflow/logs
      - ./dags:/opt/airflow/dags:cached
      - ./plugins:/opt/airflow/plugins:cached
      - ./config.yml:/opt/airflow/config.yml:cached
      - ./dbt/real_estate_dbt:/opt/airflow/projects/real_estate_dbt:cached
      - ./sql_project:/opt/airflow/projects/sql_project:cached
    command: scheduler

  airflow-init:
    image: airflow:dbt
    depends_on:
      - postgres
    env_file:
      - ./.env
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
    entrypoint: ["/bin/bash", "-c"]
    command:
      - |
        airflow db init

volumes:
  postgres_db_volume:
  airflow_logs:
